version: '3.8'

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/hexapp/static
      - media_volume:/usr/src/hexapp/media
    expose:
      - 8000
    env_file:
      - ./backend/.env
    command: gunicorn hexapp.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/hexapp/static
      - media_volume:/usr/src/hexapp/media
    ports:
      - 80:80
    depends_on:
      - django
volumes:
  postgres_data:
  static_volume:
  media_volume: